export const ONBOARD_SET_USER = 'ONBOARD_SET_USER';
export const ONBOARD_SET_USER_CLOSE_MODAL = 'ONBOARD_SET_USER_CLOSE_MODAL';
export const ONBOARD_SET_USER_OPEN_MODAL = 'ONBOARD_SET_USER_OPEN_MODAL';
export const ONBOARD_SET_USER_START_SEND_SMS =
  'ONBOARD_SET_USER_START_SEND_SMS';
export const ONBOARD_SET_USER_SUCCESS_SEND_SMS =
  'ONBOARD_SET_USER_SUCCESS_SEND_SMS';
export const ONBOARD_SET_USER_FAIL_SEND_SMS = 'ONBOARD_SET_USER_FAIL_SEND_SMS';
export const ONBOARD_USER_START = 'ONBOARD_USER_START';
export const ONBOARD_USER_END = 'ONBOARD_USER_END';

export const ONBOARD_SET_INEDATA = 'ONBOARD_SET_INEDATA';
export const ONBOARD_SET_CURPDATA = 'ONBOARD_SET_CURPDATA';
export const ONBOARD_SET_RFCDATA = 'ONBOARD_SET_RFCDATA';

export const ONBOARD_SMS_CLOSE_MODAL = 'ONBOARD_SMS_CLOSE_MODAL';
export const ONBOARD_SMS_OPEN_MODAL = 'ONBOARD_SMS_OPEN_MODAL';

export const ONBOARD_SET_SELFIE_DATA = 'ONBOARD_SET_SELFIE_DATA';
export const ONBOARD_SET_ACTIVE_IMAGE = 'ONBOARD_SET_ACTIVE_IMAGE';
export const ONBOARD_SELFIE_OPEN_MODAL = 'ONBOARD_SELFIE_OPEN_MODAL';
export const ONBOARD_SELFIE_CLOSE_MODAL = 'ONBOARD_SELFIE_CLOSE_MODAL';
export const ONBOARD_SELFIE_START = 'ONBOARD_SELFIE_START';
export const ONBOARD_SELFIE_END = 'ONBOARD_SELFIE_END';

export const ONBOARD_SET_ADDRESS_DATA = 'ONBOARD_SET_ADDRESS_DATA';
export const ONBOARD_ADDRESS_OPEN_MODAL = 'ONBOARD_ADDRESS_OPEN_MODAL';
export const ONBOARD_ADDRESS_CLOSE_MODAL = 'ONBOARD_ADDRESS_CLOSE_MODAL';

export const ONBOARD_SET_PROVIDER = 'ONBOARD_SET_PROVIDER';

export const ONBOARD_SET_BENEFICIARY = 'ONBOARD_SET_BENEFICIARY';
export const ONBOARD_BENEFICIARY_OPEN_MODAL = 'ONBOARD_BENEFICIARY_OPEN_MODAL';
export const ONBOARD_BENEFICIARY_CLOSE_MODAL =
  'ONBOARD_BENEFICIARY_CLOSE_MODAL';

export const ONBOARD_SET_DOCUMENT_DATA = 'ONBOARD_SET_DOCUMENT_DATA';
export const ONBOARD_SET_ACTIVE_DOCUMENT = 'ONBOARD_SET_ACTIVE_DOCUMENT';

export const ONBOARD_SET_SIGNATURE = 'ONBOARD_SET_SIGNATURE';

export const ONBOARD_SET_PASSWORD = 'ONBOARD_SET_PASSWORD';
export const ONBOARD_PASSWORD_OPEN_MODAL = 'ONBOARD_PASSWORD_OPEN_MODAL';
export const ONBOARD_PASSWORD_CLOSE_MODAL = 'ONBOARD_PASSWORD_CLOSE_MODAL';
export const ONBOARD_PASSWORD_START = 'ONBOARD_PASSWORD_START';
export const ONBOARD_PASSWORD_END = 'ONBOARD_PASSWORD_END';

export const ONBOARD_OPEN_MODAL = 'ONBOARD_OPEN_MODAL';
export const ONBOARD_CLOSE_MODAL = 'ONBOARD_CLOSE_MODAL';
export const ONBOARD_START_LOADING = 'ONBOARD_START_LOADING';
export const ONBOARD_END_LOADING = 'ONBOARD_END_LOADING';

export const ONBOARD_SET_CREDENCIALS = 'ONBOARD_SET_CREDENCIALS';
export const ONBOARD_SET_LASTDATA = 'ONBOARD_SET_LASTDATA';

export const ONBOARD_SET_ADDRESS2_DATA = 'ONBOARD_SET_ADDRESS2_DATA';
export const ONBOARD_SET_VIDEO_DATA = 'ONBOARD_SET_VIDEO_DATA';
export const ONBOARD_SET_VIDEO_ACTIVE = 'ONBOARD_SET_VIDEO_ACTIVE';
export const ONBOARD_SET_VIDEO_ONPRESS = 'ONBOARD_SET_VIDEO_ONPRESS';

export const ONBOARD_SET_VIDEOCALL_DATA = 'ONBOARD_SET_VIDEOCALL_DATA';
export const ONBOARD_SET_DOMICILE_DATA = 'ONBOARD_SET_DOMICILE_DATA';

export const ONBOARD_SET_ONPRESS = 'ONBOARD_SET_ONPRESS';
